sudo: required
services:
  - docker

before_install:
  - docker build -t mikesheehan90/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikesheehan90/docker-react npm run test -- --coverage

#  deploy:
#    provider: elasticbeanstalk
#    region: "us-east-2"
#    app: "docker-react"
#    env: "docker-react-env"
#    bucket_name: "elasticbeanstalk-us-east-2-3062738628"
#    bucket_path: "docker-react"
#    on:
#      branch: master